@startuml
left to right direction
 
actor "Advogada" as Advogada
 
 
rectangle " Sistema Themis"{
    usecase "Agendamento de consulta" as UC1
    usecase "Login Usuario" as UC2
    usecase "Cadastrar Cliente" as UC3
    usecase "Notificação Status" as UC4
    usecase "Status de Processo" as UC5
    usecase "Consulta Posição Financeira" as UC6
    
   
    
       
}


Advogada --> UC1
Advogada --> UC2
Advogada --> UC4
Advogada --> UC5
Advogada --> UC6

UC5 --> UC4:<<include>>
UC2 --> UC3:<<include>>
 
@enduml