@startuml
 
class Advogada {
    //Atributos da classe Advogada
    -cpf:varchar
    -nomeCompleto:varchar
    -dataNascimento:date
    -telefone:varchar
    -email:varchar
    -cep:varchar
    -logradouro:varchar
    -numero:varchar
    -complemento:varchar
    -bairro:varchar
    -cidade:varchar
    -estado:varchar
    //metodo da classe Advogada
    -LoginUsuario()
    -agendarConsulta()
    -inserirCliente()
    -alterarCliente()
    -lerCliente()
    -deletarCliente()
    -definirStatusProcesso()
    -notificaçãoStatus()
    -alterarStatusProcesso
    -contratoHOnorario()
    -pagamentoTipoProcesso()
    -consultadePosiçãoFinanceira()
    
}
 
class  Processo {
    //Atributos da classe Processo
    -id:varchar
    -numero processo
    -idCliente:varchar
    -dataAbertura:date
    -dataConclusão:date
    -Descrição:varchar
    -status:varchar
    //metodo da classe Processo
    -contratoHOnorario()
    -alterar_StatusdoProcesso()
    -definir_StatusdoProcesso()
    
   
}

class Cliente {
    //Atributos da classe cliente
    -id:varchar
    -cpf:varchar
    -nomeCompleto:varchar
    -dataNascimento:date
    -telefone:varchar
    -email:varchar
    -cep:varchar
    -logradouro:varchar
    -numero:varchar
    -complemento:varchar
    -bairro:varchar
    -cidade:varchar
    -estado:varchar
    -dataCadastro:date
    //Para Pessoa Jurídica:
    -razãoSocial:varchar
    -nomeFantasia:varchar
    -cnpj:varchar
    -inscriçãoEstadual:varchar
    -nomeResponsável:varchar
    //metodo da classe Cliente
    -LoginUsuario()
    -statusdeProcesso()
    -consultadePosiçãoFinanceira()
   
}
 
@endum
 